"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";

type User = {
  id: string;
  profileName: string;
  username: string;
  image?: string | null;
};

type Message = {
  id: string;
  content: string;
  senderId: string;
  receiverId: string;
  type?: string | null;
  mediaUrl?: string | null;
  callId?: string | null;
  createdAt: string;
};

const normalizeCallType = (value?: string | null): "audio" | "video" =>
  value === "audio" ? "audio" : "video";

const getDefaultContentByType = (
  type: "text" | "audio" | "video" | "image" | "voice"
) => {
  if (type === "audio") return "رسالة صوتية";
  if (type === "video") return "فيديو";
  if (type === "image") return "صورة";
  if (type === "voice") return "رسالة صوتية";
  return "";
};

const isAutoGeneratedMediaText = (content: string, type?: string | null) => {
  if (!type) return false;
  const defaults = ["رسالة صوتية", "فيديو", "صورة"];
  return defaults.includes(content.trim());
};

export default function ChatPage() {
  const supabase = useMemo(() => getSupabaseBrowserClient(), []);
  const router = useRouter();
  const { id: receiverIdParam } = useParams();
  const receiverId = Array.isArray(receiverIdParam)
    ? receiverIdParam[0]
    : receiverIdParam;

  const [me, setMe] = useState<User | null>(null);
  const [receiver, setReceiver] = useState<User | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [newMessage, setNewMessage] = useState("");
  const [sending, setSending] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [selectedPreview, setSelectedPreview] = useState<string | null>(null);
  const [recording, setRecording] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const mediaInputRef = useRef<HTMLInputElement>(null);
  const recorderRef = useRef<MediaRecorder | null>(null);
  const recorderChunksRef = useRef<Blob[]>([]);

  useEffect(() => {
    let isMounted = true;

    const init = async () => {
      const {
        data: { user: authUser },
      } = await supabase.auth.getUser();

      if (!authUser) {
        router.push("/signup");
        return;
      }

      const [{ data: myData }, { data: receiverData }] = await Promise.all([
        supabase
          .from("User")
          .select("id, profileName, username, image")
          .eq("id", authUser.id)
          .single(),
        supabase
          .from("User")
          .select("id, profileName, username, image")
          .eq("id", receiverId)
          .maybeSingle(),
      ]);

      const res = await fetch(
        `/api/messages?userId=${authUser.id}&receiverId=${receiverId}`
      );

      const msgs = res.ok ? ((await res.json()) as Message[]) : [];

      if (isMounted) {
        setMe((myData as User) || null);
        setReceiver((receiverData as User) || null);
        setMessages(msgs);
      }
    };

    if (receiverId) {
      init();
    }

    return () => {
      isMounted = false;
    };
  }, [receiverId, router, supabase]);

  useEffect(() => {
    if (!me || !receiverId) {
      return;
    }

    const channel = supabase
      .channel(`chat:${me.id}:${receiverId}`)
      .on(
        "postgres_changes",
        { event: "INSERT", schema: "public", table: "Message" },
        (payload: { new: Message }) => {
          const msg = payload.new;

          const isCurrentChat =
            (msg.senderId === me.id && msg.receiverId === receiverId) ||
            (msg.senderId === receiverId && msg.receiverId === me.id);

          if (!isCurrentChat) {
            return;
          }

          setMessages((prev) => {
            const exists = prev.some(
              (entry) =>
                entry.id === msg.id ||
                (entry.content === msg.content &&
                  entry.senderId === msg.senderId &&
                  entry.receiverId === msg.receiverId &&
                  entry.id.startsWith("temp-"))
            );

            if (exists) {
              return prev.map((entry) =>
                entry.id.startsWith("temp-") &&
                entry.content === msg.content &&
                entry.senderId === msg.senderId &&
                entry.receiverId === msg.receiverId
                  ? msg
                  : entry
              );
            }

            return [...prev, msg];
          });

          if (
            (msg.type === "audio" || msg.type === "video") &&
            msg.senderId === receiverId &&
            msg.callId
          ) {
            const accepted = window.confirm(
              `${receiver?.profileName || "مستخدم"} يتصل بك. هل تريد الرد؟`
            );

            if (accepted) {
              router.push(
                `/call/${msg.callId}?type=${normalizeCallType(msg.type)}`
              );
            }
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [me, receiverId, receiver, router, supabase]);

  useEffect(() => {
    scrollRef.current?.scrollIntoView({ behavior: "auto" });
  }, [messages]);

  useEffect(() => {
    return () => {
      if (selectedPreview) {
        URL.revokeObjectURL(selectedPreview);
      }
    };
  }, [selectedPreview]);

  const clearSelectedMedia = () => {
    if (selectedPreview) {
      URL.revokeObjectURL(selectedPreview);
    }
    setSelectedFile(null);
    setSelectedPreview(null);
    if (mediaInputRef.current) {
      mediaInputRef.current.value = "";
    }
  };

  const uploadMedia = async (file: File) => {
    if (!me) {
      throw new Error("المستخدم غير مسجل");
    }

    const fileExt = file.name.split(".").pop() || "bin";
    const filePath = `messages/${me.id}/${Date.now()}-${crypto.randomUUID()}.${fileExt}`;

    const { error } = await supabase.storage.from("posts").upload(filePath, file);
    if (error) {
      throw error;
    }

    const { data } = supabase.storage.from("posts").getPublicUrl(filePath);
    return data.publicUrl;
  };

  const sendMessage = async (
    type: "text" | "audio" | "video" | "image" | "voice" = "text",
    callId?: string,
    mediaUrl?: string,
    explicitContent?: string
  ) => {
    const isCall = type === "audio" || type === "video";
    const isMedia = !!mediaUrl;
    const content = isCall
      ? type === "audio"
        ? "مكالمة صوتية"
        : "مكالمة فيديو"
      : explicitContent?.trim() ||
        newMessage.trim() ||
        (isMedia
          ? getDefaultContentByType(
              type as "text" | "audio" | "video" | "image" | "voice"
            )
          : "");

    if ((!content && !mediaUrl) || !me || !receiverId || sending) {
      return;
    }

    setSending(true);
    if (!isCall && !isMedia) {
      setNewMessage("");
    }

    const tempId = `temp-${crypto.randomUUID()}`;
    const tempMessage: Message = {
      id: tempId,
      content,
      senderId: me.id,
      receiverId,
      type,
      callId: callId || null,
      mediaUrl: mediaUrl || null,
      createdAt: new Date().toISOString(),
    };

    setMessages((prev) => [...prev, tempMessage]);

    try {
      const res = await fetch("/api/messages/send", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          senderId: me.id,
          receiverId,
          text: content,
          type,
          callId: callId || null,
          mediaUrl: mediaUrl || null,
        }),
      });

      if (!res.ok) {
        throw new Error("Failed to send message");
      }

      const savedMessage = (await res.json()) as Message;

      setMessages((prev) =>
        prev.map((msg) => (msg.id === tempId ? savedMessage : msg))
      );

      if (isCall && savedMessage.callId) {
        router.push(
          `/call/${savedMessage.callId}?type=${normalizeCallType(savedMessage.type)}`
        );
      }
    } catch (error) {
      console.error(error);
      setMessages((prev) => prev.filter((msg) => msg.id !== tempId));
      if (!isCall && !isMedia) {
        setNewMessage(content);
      }
    } finally {
      setSending(false);
    }
  };

  const handlePickMedia = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    if (selectedPreview) {
      URL.revokeObjectURL(selectedPreview);
    }
    setSelectedFile(file);
    setSelectedPreview(URL.createObjectURL(file));
  };

  const sendSelectedMedia = async () => {
    if (!selectedFile) {
      return;
    }

    const mediaType = selectedFile.type.startsWith("image/")
      ? "image"
      : selectedFile.type.startsWith("video/")
      ? "video"
      : "voice";

    try {
      const mediaUrl = await uploadMedia(selectedFile);
      await sendMessage(
        mediaType as "text" | "audio" | "video" | "image" | "voice",
        undefined,
        mediaUrl,
        mediaType === "voice" ? "رسالة صوتية" : undefined
      );
      clearSelectedMedia();
      setNewMessage("");
    } catch (error) {
      console.error("Media upload/send error", error);
      alert("فشل رفع الوسائط، حاول مرة أخرى");
    }
  };

  const startCall = (type: "audio" | "video") => {
    const callId = crypto.randomUUID();
    sendMessage(type, callId);
  };

  const toggleAudioRecording = async () => {
    if (recording) {
      recorderRef.current?.stop();
      setRecording(false);
      return;
    }

    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const recorder = new MediaRecorder(stream);
      recorderChunksRef.current = [];

      recorder.ondataavailable = (event) => {
        if (event.data.size > 0) {
          recorderChunksRef.current.push(event.data);
        }
      };

      recorder.onstop = () => {
        const audioBlob = new Blob(recorderChunksRef.current, {
          type: "audio/webm",
        });
        const audioFile = new File([audioBlob], `voice-${Date.now()}.webm`, {
          type: "audio/webm",
        });

        setSelectedFile(audioFile);
        setSelectedPreview(URL.createObjectURL(audioBlob));
        stream.getTracks().forEach((track) => track.stop());
      };

      recorder.start();
      recorderRef.current = recorder;
      setRecording(true);
    } catch (error) {
      console.error("Audio recording error", error);
      alert("تعذر تشغيل المايكروفون");
    }
  };

  return (
    <div className="fixed inset-0 flex min-h-0 flex-col overflow-hidden bg-[#edf3ef]" dir="rtl">
      <header className="sticky top-0 z-20 border-b border-white/60 bg-white/90 px-4 py-3 shadow-sm backdrop-blur-xl dark:border-slate-800 dark:bg-slate-900/90">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-3">
          <button
            onClick={() => router.back()}
            className="rounded-full bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-200 dark:bg-slate-800 dark:text-white"
            type="button"
          >
            رجوع
          </button>

          <button
            onClick={() => router.push(`/profile/${receiverId}`)}
            className="flex items-center gap-3 rounded-2xl px-3 py-2 transition hover:bg-slate-100 dark:hover:bg-slate-800"
            type="button"
          >
            <img
              src={receiver?.image || "/user.png"}
              alt={receiver?.profileName || "User"}
              className="h-11 w-11 rounded-full object-cover"
            />
            <div className="text-right">
              <h1 className="font-bold text-slate-900 dark:text-white">
                {receiver?.profileName || "User"}
              </h1>
              <p className="text-xs text-emerald-600">
                @{receiver?.username || "chat"}
              </p>
            </div>
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={() => startCall("audio")}
              className="rounded-full bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-200 dark:bg-slate-800 dark:text-white"
              type="button"
            >
              📞
            </button>

            <button
              onClick={() => startCall("video")}
              className="rounded-full bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-200 dark:bg-slate-800 dark:text-white"
              type="button"
            >
              📹
            </button>
          </div>
        </div>
      </header>

      <div className="mx-auto flex w-full max-w-3xl min-h-0 flex-1 flex-col overflow-hidden">
        <div className="flex-1 overflow-y-auto px-4 py-5 overscroll-contain">
          <div className="space-y-4">
            {messages.map((msg) => {
              const isMine = msg.senderId === me?.id;
              const isCall = msg.type === "audio" || msg.type === "video";

              return (
                <div
                  key={msg.id}
                  className={`flex ${isMine ? "justify-start" : "justify-end"}`}
                >
                  {isCall && msg.callId ? (
                    <button
                      type="button"
                      onClick={() =>
                        router.push(
                          `/call/${msg.callId}?type=${normalizeCallType(msg.type)}`
                        )
                      }
                      className="max-w-[78%] cursor-pointer rounded-[22px] bg-amber-100 px-4 py-3 text-sm leading-7 text-amber-800 shadow-sm transition hover:opacity-90 dark:bg-amber-900/30 dark:text-amber-200"
                    >
                      {msg.content}
                    </button>
                  ) : (
                    <div
                      className={`max-w-[78%] rounded-[22px] px-4 py-3 text-sm leading-7 shadow-sm ${
                        isMine
                          ? "rounded-br-md bg-emerald-600 text-white"
                          : "rounded-bl-md border border-white/70 bg-white text-slate-800 dark:border-slate-800 dark:bg-slate-900 dark:text-white"
                      }`}
                    >
                      {msg.mediaUrl ? (
                        msg.type === "image" ? (
                          <img
                            src={msg.mediaUrl}
                            alt="media"
                            className="mb-2 max-h-60 w-full rounded-2xl object-cover"
                          />
                        ) : msg.type === "video" ? (
                          <video
                            src={msg.mediaUrl}
                            controls
                            className="mb-2 max-h-60 w-full rounded-2xl bg-black"
                          />
                        ) : msg.type === "voice" ? (
                          <audio src={msg.mediaUrl} controls className="mb-2 w-full" />
                        ) : (
                          <a
                            href={msg.mediaUrl}
                            target="_blank"
                            rel="noreferrer"
                            className="mb-2 inline-block text-emerald-600 underline"
                          >
                            عرض الملف
                          </a>
                        )
                      ) : null}
                      {!isAutoGeneratedMediaText(msg.content, msg.type) || !msg.mediaUrl
                        ? msg.content
                        : null}
                    </div>
                  )}
                </div>
              );
            })}
            <div ref={scrollRef} />
          </div>
        </div>

        <div className="sticky bottom-0 border-t border-white/60 bg-white/90 p-4 pb-[max(1rem,env(safe-area-inset-bottom))] backdrop-blur-xl dark:border-slate-800 dark:bg-slate-900/90">
          {selectedFile ? (
            <div className="mx-auto mb-3 flex max-w-3xl items-center justify-between rounded-2xl border border-emerald-200 bg-emerald-50 p-3 dark:border-emerald-800/40 dark:bg-emerald-900/20">
              <div className="max-w-[70%]">
                <p className="truncate text-xs font-semibold text-emerald-700 dark:text-emerald-300">
                  {selectedFile.name}
                </p>
                {selectedPreview && selectedFile.type.startsWith("image/") ? (
                  <img
                    src={selectedPreview}
                    alt="preview"
                    className="mt-2 h-16 w-16 rounded-xl object-cover"
                  />
                ) : null}
                {selectedPreview && selectedFile.type.startsWith("video/") ? (
                  <video src={selectedPreview} className="mt-2 h-16 w-20 rounded-xl object-cover" />
                ) : null}
                {selectedPreview && selectedFile.type.startsWith("audio/") ? (
                  <audio src={selectedPreview} controls className="mt-2 w-full" />
                ) : null}
              </div>
              <button
                type="button"
                onClick={clearSelectedMedia}
                className="rounded-full bg-white px-4 py-2 text-xs font-bold text-slate-700 dark:bg-slate-800 dark:text-white"
              >
                إزالة
              </button>
            </div>
          ) : null}

          <div className="mx-auto flex max-w-3xl gap-3">
            <input
              value={newMessage}
              onChange={(e) => setNewMessage(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && sendMessage()}
              placeholder="اكتب رسالة..."
              className="flex-1 rounded-full bg-slate-100 px-5 py-3 text-sm outline-none transition focus:bg-white dark:bg-slate-800 dark:text-white dark:focus:bg-slate-800"
              disabled={sending}
            />
            <button
              onClick={() => sendMessage()}
              className="rounded-full bg-emerald-600 px-6 py-3 text-sm font-bold text-white transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-60"
              type="button"
              disabled={sending}
            >
              {sending ? "جارٍ..." : "إرسال"}
            </button>

            <input
              ref={mediaInputRef}
              type="file"
              accept="image/*,video/*,audio/*"
              hidden
              onChange={handlePickMedia}
            />

            <button
              type="button"
              onClick={() => mediaInputRef.current?.click()}
              className="rounded-full bg-slate-100 px-4 py-3 text-sm font-bold text-slate-700 transition hover:bg-slate-200 dark:bg-slate-800 dark:text-white"
              disabled={sending}
            >
              📎
            </button>

            <button
              type="button"
              onClick={toggleAudioRecording}
              className={`rounded-full px-4 py-3 text-sm font-bold text-white transition ${
                recording ? "bg-red-500 hover:bg-red-600" : "bg-slate-700 hover:bg-slate-800"
              }`}
              disabled={sending}
            >
              {recording ? "⏹️" : "🎤"}
            </button>

            {selectedFile ? (
              <button
                type="button"
                onClick={sendSelectedMedia}
                className="rounded-full bg-emerald-500 px-4 py-3 text-sm font-bold text-white transition hover:bg-emerald-600"
                disabled={sending}
              >
                رفع
              </button>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  );
}